#!/bin/bash
f=B2Dh_D2KKpipi_102nd_LHCb_Week_9thDecember2021.tex
if pdflatex $f
then
  cd fgraph
  MPFILES=`ls *.mp`
  for MP in ${MPFILES}; do
    mpost ${MP}
  done
  cd ..
  pdflatex $f
fi
rm *.aux *.log *.nav *.out *.snm *.toc
